version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: dTalentschmiede
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 23bovCCq#
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_backup:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./dTalentschmiede
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/dTalentschmiede
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 23bovCCq#
    ports:
      - "8085:8085"
    depends_on:
      - database

  frontend:
    build:
      context: ./dtalentschmiede_frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  postgres_data:
